### ISSUE TITLE
Unit tests and misc

### ISSUE THREAD

**Issue by itsdfish** [taylor-curley/HyGene.jl#2]
Hey Taylor. I received a notification that you updated the repo. I have been interested in learning more about HyGene. Would it be useful for me to go through the code, make a few updates, and add some unit tests?

**Comment by taylor-curley** [comment]
It definitely would be! There is still a lot that I need to do, but any help would be great.

There are 2 approaches to the HyGene code: You can either run simulations using a numeric approach (i.e., building + manipulating numeric vectors) or by using an idiomatic approach, where information and components of memory traces and hypotheses are labeled.

I am trying to replicate Simulation 1 from the [Thomas et al. (2008) paper](https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=4fcbe1d62b062d71c61b7dd3a64cbc3437fb7fa7), but I am not getting the same results using either approach. That is what I am looking at at the moment.

**Comment by itsdfish** [comment]
Sounds good!

I will familiarize myself with the code and see if I can help with simulation 1 once I get up to speed. 

I have been using JuliaFormater.jl to apply Blue Code formatting to my code. It looks like there is a [Github Action](https://github.com/julia-actions/julia-format?tab=readme-ov-file), which automates the process and creates PRs. Would you be interesting in something like that? If so, I will submit that as a separate PR.
