### ISSUE TITLE
Conditional echo intensity in Appendix

### ISSUE THREAD

**Issue by itsdfish** [taylor-curley/HyGene.jl#6]
Hey Taylor, 

I am working through the example in the Appendix. I was able to replicate the calculations up to figure A7. In scenarios 4 and 5, H3 has a stated echo intensity of .267, but I get a different value. Are you able to replicate the  .267?

**Comment by itsdfish** [comment]
@taylor-curley, I am obtaining a similar value with Rick's code. If you don't mind, please look over the code below to see if it matches figures A6 and A7:
```
semantic_memory = np.array([
    [0, 1, -1, 1, 0, 1, -1, 1, 0, 1, -1, 0, 0, 1, 1, -1, 1, 0],
    [-1, 0, -1, 1, -1, 1, 1, 1, 0, 1, -1, 0, 0, 0, 1, 0, 1, 0],
    [1, 0, -1, -1, 1, 1, -1, 0, 0, 1, 0, 0, 0, 0, 1, -1, 1, 0],
])
# semantic probe for H3
semantic_probe = semantic_memory[2,9:]
echoIntensity(semantic_probe, hypothesis_traces) / 6
```
**output**

`0.35481481481481475
`

**Comment by taylor-curley** [comment]
I just fixed the trace decay functions as well as the SOC, so this might be fixed under this update. Also, Rick's code suggests that when values in trace vectors are replaced (`trace_replication`), they are replaced with `0.0` instead of a new value sampled from `[-1 0 1]`. I haven't done so, but changing this element in `trace_replication` may help get Fig A6/A7 value

**Comment by itsdfish** [comment]
> they are replaced with `0.0` instead of a new value sampled from `[-1 0 1]`

I assumed they were replaced with zeros, similar to encoding fidelity. But looking back at the paper, I can see how you would be confused. It doesn't seem clear either way. 

``

> changing this element in `trace_replication` may help get Fig A6/A7 value

Unfortunately, the conditional echo intensity value for H3 is a separate issue. The values in the traces are fixed in the example (see the tables throughout the appendix). Changing `trace_replication` won't solve that problem unfortunately.

**Comment by taylor-curley** [comment]
I was able to replicate the values in the Appendix (`"./model/appendix_example.jl"`). In doing so, I noticed that I need to go back and rework the echo content/intensity calculations. The data and hypothesis vectors are calculated separately in the paper, but not in the code.

**Comment by itsdfish** [comment]
Thanks Taylor. Two points below. 

> I was able to replicate the values in the Appendix (`"./model/appendix_example.jl"`).

Do you mean you were able to replicate my value of .354, or the value in the paper of .267? You were only printing out the first value, which agrees with the paper, but you can see that your calculations also do not agree:

```
julia> cond_echo_int = mean(cond_echo_int)
0.35481481481481486
```



> In doing so, I noticed that I need to go back and rework the echo content/intensity calculations

The calculations in the appendix were different from the main paper (or at least my interpretation). So I can see why you setup the code the way you did. Last weekend I already made those [corrections](https://github.com/itsdfish/HyGene.jl/tree/type_changes/src) . I was holding off on submitting a PR until the conditional echo intensity issue was resolved.

**Comment by taylor-curley** [comment]
Clearly I'm off the mark! If you feel comfortable submitting a PR, then please do so =)

**Comment by itsdfish** [comment]
Just a quick summary for future reference. We independently produced the same value for H3, which differs from the value reported in the paper. After careful review, it seems like the paper reported the wrong number. Please reopen if this is not true.
